name: live_configuration
description: A live configuration client that allows you to sync configuration entries from a remote server.
version: 1.0.1
homepage: https://github.com/TomasWeg/live-configuration

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  protobuf: ^2.0.0
  http: ^0.13.3
  fixnum: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.9
